// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA384_GTt2i4Y9sfSZuOSPi_Of1DKkxegQ',
    appId: '1:154737617568:android:79f3fe8eae288bf39fb7c5',
    messagingSenderId: '154737617568',
    projectId: 'fruit-hub-40387',
    storageBucket: 'fruit-hub-40387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4KPSLRPC_DquLAcrOFfzxeA5cLffTDM',
    appId: '1:154737617568:ios:92aed076100877119fb7c5',
    messagingSenderId: '154737617568',
    projectId: 'fruit-hub-40387',
    storageBucket: 'fruit-hub-40387.appspot.com',
    iosBundleId: 'com.example.fruitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4KPSLRPC_DquLAcrOFfzxeA5cLffTDM',
    appId: '1:154737617568:ios:92aed076100877119fb7c5',
    messagingSenderId: '154737617568',
    projectId: 'fruit-hub-40387',
    storageBucket: 'fruit-hub-40387.appspot.com',
    iosBundleId: 'com.example.fruitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXljViqahLOXe8YFdzc9DaULvz3COYxBU',
    appId: '1:154737617568:web:aa3d68bb97637cb29fb7c5',
    messagingSenderId: '154737617568',
    projectId: 'fruit-hub-40387',
    authDomain: 'fruit-hub-40387.firebaseapp.com',
    storageBucket: 'fruit-hub-40387.appspot.com',
    measurementId: 'G-K5KY6BFS1D',
  );
}
